### ISSUE TITLE
where to get .deb

### ISSUE THREAD

**Issue by kopax** [go-zookeeper/zk#121] opened 2024-02-05 21:41 UTC
Hello, i had a workaround here https://github.com/eBayClassifiedsGroup/PanteraS/issues/299#issuecomment-535903925

Somehow I trusted github to store the information I needed as usually people archive their repo

It seems the owner didn't think people needed legacy support #50 
How to get the .deb from this new repo please :) !

**Comment by jeffbean** [comment] 2024-02-05 22:37
I'm not following on what the issue is? 

This particular Go library is not a cli, or is not distributed via Debian.

**Comment by jeffbean** [comment] 2024-04-12 21:49
closing. This library is the core library that the cli you link uses. https://github.com/openark/zookeepercli/blob/master/zk/zk.go#L25

This repository itself will not provide a Debian of anything since its a pure Go library.

**Closed by jeffbean** 2024-04-12 21:49 UTC
