### ISSUE TITLE
Connection request from old client /172.20.0.1:42922; will be dropped if server is in r-o mode

### ISSUE THREAD

**Issue by domgolonka** [go-zookeeper/zk#42] opened 2020-11-12 00:03 UTC
Not working with ZK version 3.4.9.

**Comment by nemith** [comment] 2020-11-12 01:36
Can you provide steps to reproduce this issue?

**Comment by nemith** [comment] 2020-11-30 19:16
@domgolonka  Can you provide more information on this issue?  (What exactly the issue is, how to recreate it, etc?)

**Comment by nemith** [comment] 2021-03-26 16:07
Closing due to lack of information.

**Closed by nemith** 2021-03-26 16:07 UTC
Labels: need info
