### ISSUE TITLE
How about add `context` feature

### ISSUE THREAD

**Issue by Mrliu8023** [go-zookeeper/zk#48] opened 2021-02-02 07:47 UTC

**Comment by pmazzini** [comment] 2021-02-02 09:22
This is similar to https://github.com/go-zookeeper/zk/issues/12

**Comment by nemith** [comment] 2021-02-03 04:43
Is cancellation your main use case for context or something else?

**Comment by Mrliu8023** [comment] 2021-02-14 05:17
> Is cancellation your main use case for context or something else?

OCD obsessive-compulsive disorder

**Comment by nemith** [comment] 2021-03-26 16:28
OCD is not a good reason to do something :)  Closing as duplicate of #12

**Closed by nemith** 2021-03-26 16:28 UTC
Labels: duplicate
